In [22]:
import numpy as np
import matplotlib as mpl
import ipykernel 


In [23]:
theta = np.asarray([[2],[3]])
print (theta)
print(theta.shape)

[[2]
 [3]]
(2, 1)


In [24]:
x = np.asarray([[1,1],[1,2],[1,3],[1,4]])
print (x)

[[1 1]
 [1 2]
 [1 3]
 [1 4]]


In [25]:
y = np.asarray([[17],[24],[36],[43]])
print (y)

[[17]
 [24]
 [36]
 [43]]


In [26]:
y_hat = np.matmul(x, theta)
print(y_hat)
print(y_hat.shape)

[[ 5]
 [ 8]
 [11]
 [14]]
(4, 1)


In [27]:
def loss_function (y, y_hat):
    residuo = y - y_hat
    return np.matmul(residuo.T, residuo)
print (loss_function(y,y_hat))

[[1866]]


In [30]:
# One-Step Learning

# θ = (XˆT X)^-1 X^T y

primeira_mult = np.matmul(x.T, x)
pseudo_inversa = np.linalg.pinv(primeira_mult)
inversa_por_XT = np.matmul (pseudo_inversa, x.T)
best_theta = np.matmul (inversa_por_XT, y)

print(best_theta)
print(best_theta.shape)



[[7.5]
 [9. ]]
(2, 1)


In [21]:
print ('loss' , loss_function(y,np.matmul(x, theta)))
print(np.matmul(x, theta))


loss [[1866]]
[[ 5]
 [ 8]
 [11]
 [14]]


In [31]:
print ('loss' , loss_function(y,np.matmul(x, best_theta)))
print(np.matmul(x, best_theta))

loss [[5.]]
[[16.5]
 [25.5]
 [34.5]
 [43.5]]


In [ ]:
eta = 0.01 #taxa de aprendizado


