In [2]:
import numpy as np
import matplotlib as mpl
import ipykernel 


In [6]:
theta = np.asarray([[2],[3]])
print (theta)
print(theta.shape)

[[2]
 [3]]
(2, 1)


In [7]:
x = np.asarray([[1,1],[1,2],[1,3],[1,4]])
print (x)

[[1 1]
 [1 2]
 [1 3]
 [1 4]]


In [8]:
y = np.asarray([[17],[24],[36],[43]])
print (y)

[[17]
 [24]
 [36]
 [43]]


In [9]:
y_hat = np.matmul(x, theta)
print(y_hat)
print(y_hat.shape)

[[ 5]
 [ 8]
 [11]
 [14]]
(4, 1)


In [10]:
residuo = y - y_hat
loss = np.matmul(residuo.T, residuo)
print (loss)

[[1866]]
